// --- Text Replacement ---
const shortcuts = {
  "00": "There are no deficiencies or significant defects present.",
  att: "attenuators",
  b1: "Beam 1",
  b2: "Beam 2",
  b3: "Beam 3",
  b4: "Beam 4",
  b5: "Beam 5",
  b6: "Beam 6",
  b7: "Beam 7",
  b8: "Beam 8",
  b9: "Beam 9",
  b10: "Beam 10",
  b11: "Beam 11",
  b12: "Beam 12",
  b13: "Beam 13",
  b14: "Beam 14",
  b15: "Beam 15",
  b16: "Beam 16",
  b17: "Beam 17",
  b18: "Beam 18",
  b19: "Beam 19",
  b20: "Beam 20",
  bw: "backwall",
  cne: "Component was not evaluated during this inspection.",
  ch: "channel",
  cr: "cracking",
  d: "Defect:",
  d5: "Strength and performance are not affected.",
  dc6: "showing moderate cracking",
  dc7: "showing minor cracking",
  dc8: "showing inherent cracking",
  dcfe: "downstream channel facing east",
  dcfn: "downstream channel facing north",
  dcfs: "downstream channel facing south",
  dcfw: "downstream channel facing west",
  ds6: "showing moderate spalling",
  ds7: "showing minor spalling",
  e: "east",
  eab: "east abutment",
  eb: "eastbound",
  ebl: "eastbound lane",
  ef: "efflorescence",
  ejas: "east joint and approach slab",
  es: "east side",
  ese: "east end",
  fe: "facing east",
  fn: "facing north",
  fs: "facing south",
  fw: "facing west",
  fte: "facing through east",
  ftn: "facing through north",
  fts: "facing through south",
  ftw: "facing through west",
  g: "General:",
  hw: "headwall",
  i: "I",
  iim: "there is isolated minor",
  iimo: "there is isolated moderate",
  ism: "there is some minor",
  ismo: "there is some moderate",
  isolated: "isolated",
  iwm: "there is widespread minor",
  iwmo: "there is widespread moderate",
  j2: "Joint 2",
  j3: "Joint 3",
  j4: "Joint 4",
  j5: "Joint 5",
  lc: "longitudinal cracking",
  mse: "MSE wall",
  n: "north",
  no: "no",
  nab: "north abutment",
  nb: "northbound",
  nbl: "northbound lane",
  njas: "north joint and approach slab",
  ns: "north side",
  nse: "north end",
  o: "Overview:",
  p2: "Pier 2",
  p3: "Pier 3",
  p4: "Pier 4",
  p5: "Pier 5",
  p6: "Pier 6",
  p7: "Pier 7",
  p8: "Pier 8",
  p9: "Pier 9",
  p10: "Pier 10",
  p11: "Pier 11",
  p12: "Pier 12",
  p13: "Pier 13",
  p14: "Pier 14",
  p15: "Pier 15",
  p16: "Pier 16",
  p17: "Pier 17",
  p18: "Pier 18",
  p19: "Pier 19",
  p20: "Pier 20",
  "pin-": "pin-and-hinge assemblies",
  pr: "present",
  rc: "random cracking",
  re: "roadway alignment facing east",
  rn: "roadway alignment facing north",
  rs: "roadway alignment facing south",
  rw: "roadway alignment facing west",
  rr: "The bridge crosses a railroad; INDOT personnel may access the railroad right-of-way based on rule IC 8-3-15-3 (d)(8).",
  s: "south",
  s1: "Span A",
  s2: "Span B",
  s3: "Span C",
  s4: "Span D",
  s5: "Span E",
  s6: "Span F",
  s7: "Span G",
  s8: "Span H",
  s9: "Span I",
  s10: "Span J",
  s11: "Span K",
  s12: "Span L",
  s13: "Span M",
  s14: "Span N",
  s15: "Span O",
  s16: "Span P",
  s17: "Span Q",
  s18: "Span R",
  s19: "Span S",
  s20: "Span T",
  sab: "south abutment",
  sb: "southbound",
  sbl: "southbound lane",
  sipf: "stay-in-place forms",
  sjas: "south joint and approach slab",
  some: "some",
  sp: "spalling",
  ss: "south side",
  sse: "south end",
  sw: "slopewall",
  t: "Typical:",
  tc: "transverse cracking",
  the: "the",
  there: "there",
  tj: "terminal joint",
  totd: "top of the deck",
  typ: "typical",
  ucfe: "upstream channel facing east",
  ucfn: "upstream channel facing north",
  ucfs: "upstream channel facing south",
  ucfw: "upstream channel facing west",
  uotd: "underside of the deck",
  un: "underside",
  vc: "vertical cracking",
  w: "west",
  wab: "west abutment",
  wb: "westbound",
  wbl: "westbound lane",
  widespread: "widespread",
  wjas: "west joint and approach slab",
  ws: "west side",
  wse: "west end",
  ww: "wingwall",
  "1&2": "1 and 2",
  "2&3": "2 and 3",
  "3&4": "3 and 4",
  "4&5": "4 and 5",
  "5&6": "5 and 6",
  "6&7": "6 and 7",
  "7&8": "7 and 8",
  "8&9": "8 and 9",
  "9&10": "9 and 10",

  // --- Automatically Fixed Spelling Errors ---
  stagnent: "stagnant",
  stagnat: "stagnant",
  stagnet: "stagnant",
  thalwag: "thalweg",
  occured: "occurred",
  occure: "occur",
  occuring: "occurring",

  efflorecence: "efflorescence",
  diaphram: "diaphragm",
  corosion: "corrosion",

  // --- Common Typo Mispellings ---
  aroung: "around",
  becasue: "because",
  becuase: "because",
  teh: "the",
  thier: "their",
  thers: "there",
  thoes: "those",

  // Extremely common “smart person” misspellings
  definately: "definitely",
  definetly: "definitely",
  defenitely: "definitely",
  seperate: "separate",
  independant: "independent",
  recomend: "recommend",
  recomendation: "recommendation",
  enviroment: "environment",
  goverment: "government",
  arguement: "argument",
  concensus: "consensus",
  comming: "coming",
  embarass: "embarrass",
  embaras: "embarrass",
  occassion: "occasion",
  ocasional: "occasional",
  ocasionaly: "occasionally",
  adress: "address",
  adressing: "addressing",
  adresssed: "addressed",
  beleive: "believe",
  recieve: "receive",
  reciept: "receipt",
  wierd: "weird",
  acheive: "achieve",
  acheived: "achieved",
  acheiving: "achieving",
  maintenence: "maintenance",
  maintnance: "maintenance",
  maintenace: "maintenance",
  persue: "pursue",
  persuing: "pursuing",
  refered: "referred",
  refering: "referring",
  prefered: "preferred",
  prefering: "preferring",
  occured: "occurred",
  occurence: "occurrence",
  occurances: "occurrences",
  responsability: "responsibility",
  responsibile: "responsible",
  responsiblity: "responsibility",
  liason: "liaison",
  liasion: "liaison",
  calender: "calendar",
  harasment: "harassment",
  harrasment: "harassment",
  harras: "harass",
  harrasment: "harassment",

  // --- Accronyms ---

  itams: "iTAMS",
  ITAMS: "iTAMS",
  Itams: "iTAMS",

  aashto: "AASHTO",
  AASHTO: "AASHTO",

  osha: "OSHA",
  OSHA: "OSHA",

  i: "I",
  I: "I",

  ohwm: "OHWM",
  OHWM: "OHWM",

  mse: "MSE",
  MSE: "MSE",

  fhwa: "FHWA",
  FHWA: "FHWA",

  indot: "INDOT",
  INDOT: "INDOT",

  iphone: "iPhone",
  ipad: "iPad",

  lidar: "LiDAR",
  Lidar: "LiDAR",
  LIDAR: "LiDAR",

  nstm: "NSTM",
  NSTM: "NSTM",

  snbi: "SNBI",
  SNBI: "SNBI",
};

// --- Predictive Text ---
const predictiveWords = [
  "abrasion",
  "abutment",
  "adhesion",
  "adjacent",
  "affected",
  "aggradation",
  "alignment",
  "approach",
  "approximately",
  "assemblies",
  "attenuator",
  "backwall",
  "barrel",
  "bearing",
  "bituminous",
  // "box",
  "bridge",
  "buildup",
  "channel",
  "chalking",
  "column",
  "concrete",
  "condition",
  "construction",
  "coping",
  "corrosion",
  "cracking",
  "curb",
  // "deck",
  "defect",
  "deficiencies",
  "deformation",
  "degradation",
  "delamination",
  "designed",
  "deterioration",
  "diaphragm",
  "discontinuities",
  "displacement",
  "distress",
  "downs",
  "downspout",
  "downstream",
  "drainage",
  // "east",
  "eastbound",
  "efflorescence",
  "elevation",
  "erosion",
  "evaluated",
  "exposed",
  "expansion",
  "facing",
  "footing",
  "freeboard",
  "functioning",
  "girder",
  "guardrail",
  "headwall",
  "honeycombing",
  "horizontal",
  "hydraulic",
  "impacted",
  "instability",
  "insignificant",
  "inspection",
  "interior",
  "invert",
  "isolated",
  "joint",
  "leakage",
  "localized",
  "longitudinal",
  "measurements",
  "membrane",
  "minor",
  "misaligned",
  "moderate",
  "movement",
  "necessary",
  // "north",
  "northbound",
  "noticeable",
  "observations",
  "occurred",
  "overlay",
  "patching",
  "peeling",
  "performance",
  "pier",
  "pin-and-hinge",
  "pitting",
  "present",
  "profile",
  "protected",
  "quality",
  "railings",
  "random",
  "reduction",
  "reinforce",
  "reinforcement",
  "reporting",
  "right-of-way",
  "riprap",
  "roadway",
  "rutting",
  "scaling",
  "scour",
  "sediment",
  "segment",
  "settlement",
  "significant",
  "shallow-depth",
  // "slab",
  "slightly",
  "slopewall",
  "slump",
  "some",
  // "south",
  "southbound",
  "spalling",
  "stability",
  "staining",
  "stay-in-place",
  "stiffener",
  "strength",
  "stringer",
  "structure",
  "substructure",
  "super",
  "superelevated",
  "superstructure",
  "surface",
  "terminal",
  "transition",
  "transverse",
  "under",
  "undermining",
  "underside",
  "upstream",
  "vertical",
  "visually",
  "waterline",
  // "wear",
  "wearing",
  "well-graded",
  // "west",
  "westbound",
  "widespread",
  "wingwall",
];

const spellFixes = {
  stagnent: "stagnant",
  stagnat: "stagnant",
  stagnet: "stagnant",
  thalwag: "thalweg",
  occured: "occurred",
  occure: "occur",
  occuring: "occurring",

  efflorecence: "efflorescence",
  diaphram: "diaphragm",
  corosion: "corrosion",

  // --- Common Typo Mispellings ---
  aroung: "around",
  becasue: "because",
  becuase: "because",
  teh: "the",
  thier: "their",
  thers: "there",
  thoes: "those",

  // Extremely common “smart person” misspellings
  definately: "definitely",
  definetly: "definitely",
  defenitely: "definitely",
  seperate: "separate",
  independant: "independent",
  recomend: "recommend",
  recomendation: "recommendation",
  enviroment: "environment",
  goverment: "government",
  arguement: "argument",
  concensus: "consensus",
  comming: "coming",
  embarass: "embarrass",
  embaras: "embarrass",
  occassion: "occasion",
  ocasional: "occasional",
  ocasionaly: "occasionally",
  adress: "address",
  adressing: "addressing",
  adresssed: "addressed",
  beleive: "believe",
  recieve: "receive",
  reciept: "receipt",
  wierd: "weird",
  acheive: "achieve",
  acheived: "achieved",
  acheiving: "achieving",
  maintenence: "maintenance",
  maintnance: "maintenance",
  maintenace: "maintenance",
  persue: "pursue",
  persuing: "pursuing",
  refered: "referred",
  refering: "referring",
  prefered: "preferred",
  prefering: "preferring",
  occured: "occurred",
  occurence: "occurrence",
  occurances: "occurrences",
  responsability: "responsibility",
  responsibile: "responsible",
  responsiblity: "responsibility",
  liason: "liaison",
  liasion: "liaison",
  calender: "calendar",
  harasment: "harassment",
  harrasment: "harassment",
  harras: "harass",
  harrasment: "harassment",

  // --- Compound Words ---

  "passer by": "passerby",
  "sub district": "subdistrict",
  "snow plow": "snowplow",
  "widely-spaced": "widely spaced",
  "hair line": "hairline",

  "rip rap": "riprap",
  "rip-rap": "riprap",

  "head wall": "headwall",
  "back wall": "backwall",
  "wing wall": "wingwall",
  "slope wall": "slopewall",

  flowline: "flow line",
  "center line": "centerline",
  "job site": "jobsite",

  "off ramp": "off-ramp",
  "on ramp": "on-ramp",
  "right of way": "right-of-way",

  "#0": "0",
  "#1": "1",
  "#2": "2",
  "#3": "3",
  "#4": "4",
  "#5": "5",
  "#6": "6",
  "#7": "7",
  "#8": "8",
  "#9": "9",

  "  ": " ",
};

const properNouns = {
  // States
  indiana: "Indiana",
  kentucky: "Kentucky",
  ohio: "Ohio",

  // Cities
  laporte: "LaPorte",
  seymour: "Seymour",
  georgetown: "Georgetown",
  vincennes: "Vincennes",
  "new albany": "New Albany",
  "fort wayne": "Fort Wayne",
  greenfield: "Greenfield",
  louisville: "Louisville",
  columbus: "Columbus",

  // Rivers
  "ohio river": "Ohio River",
  "mississippi river": "Mississippi River",

  // Roads
  "interstate 65": "Interstate 65",
  "interstate 64": "Interstate 64",
  "us 50": "US 50",
  "state road 11": "State Road 11",

  // ===== Beam 1–14 =====
  ...Object.fromEntries(
    Array.from({ length: 14 }, (_, i) => [`beam ${i + 1}`, `Beam ${i + 1}`]),
  ),

  // ===== Beams 1–14 =====
  ...Object.fromEntries(
    Array.from({ length: 14 }, (_, i) => [`beams ${i + 1}`, `Beams ${i + 1}`]),
  ),

  // ===== Pier 1–14 =====
  ...Object.fromEntries(
    Array.from({ length: 14 }, (_, i) => [`pier ${i + 1}`, `Pier ${i + 1}`]),
  ),

  // ===== Piers 1–14 =====
  ...Object.fromEntries(
    Array.from({ length: 14 }, (_, i) => [`piers ${i + 1}`, `Piers ${i + 1}`]),
  ),

  // ===== Bent 1–14 =====
  ...Object.fromEntries(
    Array.from({ length: 14 }, (_, i) => [`bent ${i + 1}`, `Bent ${i + 1}`]),
  ),

  // ===== Bents 1–14 =====
  ...Object.fromEntries(
    Array.from({ length: 14 }, (_, i) => [`bents ${i + 1}`, `Bents ${i + 1}`]),
  ),

  // ===== Abutment 1–14 =====
  ...Object.fromEntries(
    Array.from({ length: 14 }, (_, i) => [
      `abutment ${i + 1}`,
      `Abutment ${i + 1}`,
    ]),
  ),

  // ===== Abutments 1–14 =====
  ...Object.fromEntries(
    Array.from({ length: 14 }, (_, i) => [
      `abutments ${i + 1}`,
      `Abutments ${i + 1}`,
    ]),
  ),

  // ===== Span A–Z =====
  ...Object.fromEntries(
    Array.from({ length: 26 }, (_, i) => {
      const letter = String.fromCharCode(97 + i);
      return [`span ${letter}`, `Span ${letter.toUpperCase()}`];
    }),
  ),

  // ===== Span A.–Z. =====
  ...Object.fromEntries(
    Array.from({ length: 26 }, (_, i) => {
      const letter = String.fromCharCode(97 + i);
      return [`span ${letter}.`, `Span ${letter.toUpperCase()}.`];
    }),
  ),

  // ===== Span A,–Z, =====
  ...Object.fromEntries(
    Array.from({ length: 26 }, (_, i) => {
      const letter = String.fromCharCode(97 + i);
      return [`span ${letter},`, `Span ${letter.toUpperCase()},`];
    }),
  ),

  // ===== Spans A–Z =====
  ...Object.fromEntries(
    Array.from({ length: 26 }, (_, i) => {
      const letter = String.fromCharCode(97 + i);
      return [`spans ${letter}`, `Spans ${letter.toUpperCase()}`];
    }),
  ),
};

const specialCaseWords = {
  itams: "iTAMS",
  ITAMS: "iTAMS",
  Itams: "iTAMS",

  aashto: "AASHTO",
  AASHTO: "AASHTO",

  osha: "OSHA",
  OSHA: "OSHA",

  ohwm: "OHWM",
  OHWM: "OHWM",

  mse: "MSE",
  MSE: "MSE",

  fhwa: "FHWA",
  FHWA: "FHWA",

  indot: "INDOT",
  INDOT: "INDOT",

  iphone: "iPhone",
  ipad: "iPad",
};
